### PR TITLE
Multi json

### PR DESCRIPTION
**Pull request by jtdowney**
The bundled JSON encoder in MultiJson has issues encoding objects that don't have #to_json (like Time in 1.8.7). The rails guys wrapped MultiJson with ActiveSupport::JSON to fix those issues. I've updated the references to use ActiveSupport::JSON and ran the specs on 1.8.7 and 1.9.2.

### CODE REVIEW

**Comment by cavalle** [comment]
mmm, I think I don't want Eventwire to depend on ActiveSupport just for this.

**Comment by jtdowney** [comment]
Thats fair, I just noticed there was already a dependency on activesupport in the Gemfile and though I would use it.

**Comment by jtdowney** [comment]
Although I just realized it was in the gemfile and not the gemspec. Is AS only used for testing?

**Comment by cavalle** [comment]
yes, it should only be used for testing

**Comment by jtdowney** [comment]
Then I would say close this and skip multi_json, until their built-in default can do symbols and time like the native gems. Sorry for the confusion, I didn't realize okjson was missing some things on 1.8.7.

**Pull request closed without merging**
